import React, { useRef } from 'react'
import { Float, useGLTF } from '@react-three/drei'


const Cube = (props) => {
    const { nodes, materials } = useGLTF('/models/sci-fi_cube_01.glb')
    return (
        <Float floatIntensity={2}>
            <group scale={0.08} {...props} dispose={null}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part5_Default_0.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part5_Default_0_1.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part4_Default_0.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part1_Default_0.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_1.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_2.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_3.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_4.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_5.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_6.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_7.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_8.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_9.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_10.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_11.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_12.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_13.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_14.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part5_Default_0_2.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part5_Default_0_3.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part5_Default_0_4.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part5_Default_0_5.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part5_Default_0_6.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part5_Default_0_7.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part4_Default_0_1.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part1_Default_0_1.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_15.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_16.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_17.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_18.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_19.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_20.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_21.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_22.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_23.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_24.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_25.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_26.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_27.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_28.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_29.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part5_Default_0_8.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part5_Default_0_9.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part5_Default_0_10.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part5_Default_0_11.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part5_Default_0_12.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part5_Default_0_13.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part4_Default_0_2.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part1_Default_0_2.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_30.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_31.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_32.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_33.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_34.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_35.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_36.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_37.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_38.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_39.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_40.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_41.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_42.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_43.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_44.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part5_Default_0_14.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part5_Default_0_15.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part5_Default_0_16.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part5_Default_0_17.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part5_Default_0_18.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part5_Default_0_19.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part4_Default_0_3.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part1_Default_0_3.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_45.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_46.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_47.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_48.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_49.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_50.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_51.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_52.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_53.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_54.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_55.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_56.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_57.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_58.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_59.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part5_Default_0_20.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part5_Default_0_21.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part5_Default_0_22.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part5_Default_0_23.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part5_Default_0_24.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part5_Default_0_25.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part4_Default_0_4.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part1_Default_0_4.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_60.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_61.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_62.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_63.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_64.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_65.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_66.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_67.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_68.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_69.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_70.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_71.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_72.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_73.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_74.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part5_Default_0_26.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part5_Default_0_27.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part5_Default_0_28.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part5_Default_0_29.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part5_Default_0_30.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part5_Default_0_31.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part4_Default_0_5.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part1_Default_0_5.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_75.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_76.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_77.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_78.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_79.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_80.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_81.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_82.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_83.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_84.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_85.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_86.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_87.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_88.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_89.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part5_Default_0_32.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part5_Default_0_33.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part5_Default_0_34.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part5_Default_0_35.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part5_Default_0_36.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part5_Default_0_37.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part4_Default_0_6.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part1_Default_0_6.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_90.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_91.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_92.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_93.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_94.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_95.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_96.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_97.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_98.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_99.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_100.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_101.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_102.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_103.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_104.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part5_Default_0_38.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part5_Default_0_39.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part5_Default_0_40.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part5_Default_0_41.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part5_Default_0_42.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part5_Default_0_43.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part4_Default_0_7.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part1_Default_0_7.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_105.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_106.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_107.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_108.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_109.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_110.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_111.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_112.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_113.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_114.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_115.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_116.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_117.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_118.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part3_Default_0_119.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part5_Default_0_44.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part5_Default_0_45.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part5_Default_0_46.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part5_Default_0_47.geometry}
                    material={materials.Default}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Part2_Default_0.geometry}
                    material={materials.Default}
                />
            </group>
        </Float>
    )
}

useGLTF.preload('/models/sci-fi_cube_01.glb')

export default Cube;